### ISSUE TITLE
Retrain model depending on the performance of detection model

### ISSUE THREAD

**Issue by yaboo-oyabu** [yaboo-oyabu/CarND-Capstone#24]

**Comment by yaboo-oyabu** [comment]
I retrained the inception v2 coco model.

- Dataset: tl_images_for_detection.tgz excluding DriveU (DTLD) dataset
- Model: ssd_inception_v2_sdcn_s10000.tgz
- Performance: ssd_inception_v2_sdcn_s10000_performance.tgz

All files can be found in https://drive.google.com/drive/u/1/folders/1tzspy7yyseenawGw_viyF2TL87-Tudln

Note that I split train and validation set as 9:1 ratio, and the above performance show the performance on both train and validation set.

@CaoFM @jotredi @antoska20 @xfhg

**Comment by CaoFM** [comment]
@yaboo-oyabu Looks awesome to me. I couldn't really tell the difference in result between 0.8 vs 0.6. I think because the images from rosbag is free of confusion objects.

**Comment by yaboo-oyabu** [comment]
@CaoFM @jotredi @antoska20 @xfhg 

I re-retrained the model with mixed dataset. 

- model name: ssd_inception_v2_retrained_2806
- performance: ssd_inception_v2_retrained_2806_performance

All files can be found in https://drive.google.com/drive/u/1/folders/1tzspy7yyseenawGw_viyF2TL87-Tudln

More details can be found in https://github.com/yaboo-oyabu/CarND-Capstone/tree/yaboo/real_traffic_lights_collection/models/real_tl_images
