### ISSUE TITLE
Update README so that it will contain the full names and Udacity account emails of the team members.

### ISSUE THREAD

**Issue by yaboo-oyabu** [yaboo-oyabu/CarND-Capstone#3]
A README file in .txt, .md, or .pdf format. This file should contain the full names and Udacity account emails of your team members. For additional resources on creating READMEs or using Markdown, see [here](https://guides.github.com/features/wikis/) or [here](https://guides.github.com/features/mastering-markdown/).

**Comment by jotredi** [comment]
I have updated the README with a short description of the project and the team members. Maybe we could later expand the README with a description of our implementation.

**Comment by yaboo-oyabu** [comment]
@jotredi Thanks!
