### ISSUE TITLE
A traffic light detection model for real world

### ISSUE THREAD

**Issue by yaboo-oyabu** [yaboo-oyabu/CarND-Capstone#6]
We may not need to train traffic light detection model for real world because there are many publicly available object detection models that can detect traffic lights. https://github.com/tensorflow/models/tree/master/research/object_detection

**Comment by yaboo-oyabu** [comment]
@jotredi @CaoFM @xfhg 

I tried some pre-trained models listed in [TensorFlow model](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md).
The following image was captured when I used ssd_mobilenet_v2_coco model:
![image](https://user-images.githubusercontent.com/1643282/87859202-5d78ba00-c96e-11ea-9241-724a86e38756.png)

Note that I set the lower confidence level (0.2) and display only 'traffic light' class.

**Comment by jotredi** [comment]
ok great!! yes we can use one of those models for real world images but we still need to predict the traffic light state right?

**Comment by yaboo-oyabu** [comment]
@jotredi Correct.

**Comment by yaboo-oyabu** [comment]
#12

**Comment by yaboo-oyabu** [comment]
Since my precious PR violated one of the requirements for this project, I reverted the above PR. 
I will dig into this solution in https://stackoverflow.com/questions/53927700/how-to-use-object-detection-api-with-an-old-version-of-tensorflow-v1-3-0 or https://github.com/smasoudn/traffic_light_detection.
