### ISSUE TITLE
A traffic light classification model for simulation

### ISSUE THREAD

**Issue by yaboo-oyabu** [yaboo-oyabu/CarND-Capstone#7]

**Comment by CaoFM** [comment]
I successfully built a model to train the classifier for simulator image. With little tuning the model is getting accuracy of 90% offline. 

Now working on loading the model and predict ros camera image during run-time.

**Comment by CaoFM** [comment]
@yaboo-oyabu I have a separate model for directly classify traffic light in simulator environment and it successfully goes around the highway track following traffic signals. Let me know if you would like me to just bookshelf this or pull into master to keep as an option.
